In [4]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

In [5]:
data = pd.read_csv('train.csv')

In [6]:
data

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
0,0001_01,Europa,False,B/0/P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,Maham Ofracculy,False
1,0002_01,Earth,False,F/0/S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,Juanna Vines,True
2,0003_01,Europa,False,A/0/S,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,Altark Susent,False
3,0003_02,Europa,False,A/0/S,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,Solam Susent,False
4,0004_01,Earth,False,F/1/S,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,Willy Santantines,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8688,9276_01,Europa,False,A/98/P,55 Cancri e,41.0,True,0.0,6819.0,0.0,1643.0,74.0,Gravior Noxnuther,False
8689,9278_01,Earth,True,G/1499/S,PSO J318.5-22,18.0,False,0.0,0.0,0.0,0.0,0.0,Kurta Mondalley,False
8690,9279_01,Earth,False,G/1500/S,TRAPPIST-1e,26.0,False,0.0,0.0,1872.0,1.0,0.0,Fayey Connon,True
8691,9280_01,Europa,False,E/608/S,55 Cancri e,32.0,False,0.0,1049.0,0.0,353.0,3235.0,Celeon Hontichre,False
8692,9280_02,Europa,False,E/608/S,TRAPPIST-1e,44.0,False,126.0,4688.0,0.0,0.0,12.0,Propsh Hontichre,True

In [7]:
data.isna().sum()

PassengerId       0
HomePlanet      201
CryoSleep       217
Cabin           199
Destination     182
Age             179
VIP             203
RoomService     181
FoodCourt       183
ShoppingMall    208
Spa             183
VRDeck          188
Name            200
Transported       0
dtype: int64

In [8]:
x = data.drop("Transported", axis = 1)
y = data["Transported"]

In [9]:
y.astype("int8")

0       0
1       1
2       0
3       0
4       1
       ..
8688    0
8689    0
8690    1
8691    0
8692    1
Name: Transported, Length: 8693, dtype: int8

In [10]:
x_train, x_test, y_train, y_test = train_test_split( x, y, test_size=0.25, random_state=0)
x_train

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name
5020,5363_01,Mars,True,F/1102/P,TRAPPIST-1e,37.0,False,0.0,0.0,0.0,0.0,0.0,Crowk Apeau
5967,6324_02,Earth,NaN,G/1025/S,55 Cancri e,44.0,False,0.0,0.0,0.0,0.0,0.0,Murie Hinetthews
991,1053_01,Earth,False,F/199/S,PSO J318.5-22,27.0,False,182.0,0.0,0.0,0.0,376.0,Rald Colleruces
2894,3128_01,Earth,False,G/512/P,55 Cancri e,15.0,False,62.0,57.0,2646.0,1104.0,312.0,Heila Gordond
2228,2385_01,Mars,False,F/461/S,TRAPPIST-1e,23.0,False,1773.0,0.0,78.0,0.0,3.0,Jacats PitÃ©
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4373,4655_01,Europa,True,B/154/P,55 Cancri e,32.0,False,0.0,0.0,0.0,0.0,0.0,Ainkard Seflock
7891,8423_01,Earth,False,F/1620/S,TRAPPIST-1e,22.0,False,0.0,0.0,6.0,0.0,733.0,Analdy Bartez
4859,5185_01,Mars,False,E/330/S,TRAPPIST-1e,29.0,False,523.0,0.0,21.0,4.0,811.0,Cruts Flie
3264,3499_04,Earth,False,G/574/P,TRAPPIST-1e,0.0,False,0.0,0.0,0.0,0.0,0.0,Allene Mccarveymon
2732,2930_01,Earth,False,G/474/P,TRAPPIST-1e,45.0,False,NaN,9.0,0.0,857.0,16.0,Cary Mejiaddox

In [11]:
age_med = x_train["Age"].median()
age_med

np.float64(27.0)

In [12]:
x_train["HomePlanet"] = x_train["HomePlanet"].apply(lambda x: np.random.choice(["Earth", "Europa", "Mars"], p = [0.54, 0.25, 0.21]) if isinstance(x, float) else x)

x_train["CryoSleep"] = (x_train["CryoSleep"].apply(lambda x: np.random.choice([1, 0], p = [0.36, 0.64]) if isinstance(x, float) else int(x))).astype("int8")
x_train["Destination"] = x_train["Destination"].apply(lambda x: np.random.choice(["TRAPPIST-1e", "55 Cancri e", "PSO J318.5-22"], p = [0.7, 0.21, 0.09]) if isinstance(x, float) else x)

x_train["VIP"] = x_train["VIP"].fillna(False).astype("int8")

x_train["RoomService"] = x_train["RoomService"].fillna(x_train["RoomService"].median())
x_train["FoodCourt"] = x_train["FoodCourt"].fillna(x_train["FoodCourt"].median())
x_train["ShoppingMall"] = x_train["ShoppingMall"].fillna(x_train["ShoppingMall"].median())
x_train["Spa"] = x_train["Spa"].fillna(x_train["Spa"].median())
x_train["VRDeck"] = x_train["VRDeck"].fillna(x_train["VRDeck"].median())

x_train["Cabin"] = x_train["Cabin"].str.split("/", expand=True)[2]
x_train["Cabin"] = (x_train["Cabin"] == "P").astype("int8")

C:\Users\hacat\AppData\Local\Temp\ipykernel_23196\1375064487.py:6: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  x_train["VIP"] = x_train["VIP"].fillna(False).astype("int8")

In [13]:
p = x_train["PassengerId"].str.split("_", expand=True)[0].value_counts()
p

0
5133    8
6302    7
0378    7
1148    7
8168    7
       ..
8292    1
6572    1
7339    1
6381    1
5418    1
Name: count, Length: 4968, dtype: int64

In [14]:
np.unique(p.values, return_counts=)

SyntaxError: expected argument value expression (2057694041.py, line 1)

In [ ]:
x_train

In [ ]:
x_train = pd.get_dummies(x_train, columns = ["HomePlanet"], dtype = "int8")
x_train = pd.get_dummies(x_train, columns = ["Destination"], dtype = "int8")
x_train["CryoSleep"] = x_train["CryoSleep"].astype('int8')

In [ ]:
x_train["Cabin"] = (x_train["Cabin"] == "P").astype('int8')
x_train["VIP"] = x_train["VIP"].astype('int8')

x_train

In [ ]:
x_train = x_train.drop("Name", axis = 1)

In [ ]:
x_train

In [ ]:
x_train[["Age", "RoomService", "FoodCourt", "ShoppingMall", "Spa", "VRDeck"]].hist()

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
x_train_sc = x_train[["Age", "RoomService", "FoodCourt", "ShoppingMall", "Spa", "VRDeck"]]
scl = StandardScaler()
x_train_sc = pd.DataFrame(scl.fit_transform(x_train_sc), columns = x_train_sc.columns, index = x_train_sc.index)
x_train[["Age", "RoomService", "FoodCourt", "ShoppingMall", "Spa", "VRDeck"]] = x_train_sc

In [ ]:
x_train = x_train.drop("PassengerId", axis = 1)

In [ ]:
x_test["HomePlanet"] = x_test["HomePlanet"].fillna(np.random.choice(["Earth", "Europa", "Mars"], p = [0.54, 0.25, 0.21]))
x_test["CryoSleep"] = x_test["CryoSleep"].fillna(np.random.choice([True, False], p = [0.36, 0.64]))
x_test["Destination"] = x_test["Destination"].fillna(np.random.choice(["TRAPPIST-1e", "55 Cancri e", "PSO J318.5-22"], p = [0.7, 0.21, 0.09]))
x_test["Age"] = x_test["Age"].fillna(x_train["Age"].median())
x_test["VIP"] = x_test["VIP"].fillna(np.random.choice([True, False], p = [0.02, 0.98]))
if x_test["CryoSleep"] is True :
    x_test["RoomService"] = x_test["RoomService"].fillna(x_test["RoomService"].median())
    x_test["FoodCourt"] = x_test["FoodCourt"].fillna(x_test["FoodCourt"].median())
    x_test["ShoppingMall"] = x_test["ShoppingMall"].fillna(x_test["ShoppingMall"].median())
    x_test["Spa"] = x_test["Spa"].fillna(x_test["Spa"].median())
    x_test["VRDeck"] = x_test["VRDeck"].fillna(x_test["VRDeck"].median())
else:
    x_test["RoomService"] = x_test["RoomService"].fillna(0)
    x_test["FoodCourt"] = x_test["FoodCourt"].fillna(0)
    x_test["ShoppingMall"] = x_test["ShoppingMall"].fillna(0)
    x_test["Spa"] = x_test["Spa"].fillna(0)
    x_test["VRDeck"] = x_test["VRDeck"].fillna(0)

In [ ]:
x_test["Cabin"] = x_test["Cabin"].fillna(np.random.choice(["G/1025/S", "G/512/P"]))

In [ ]:
x_test = pd.get_dummies(x_test, columns = ["HomePlanet"], dtype = "int8")
x_test = pd.get_dummies(x_test, columns = ["Destination"], dtype = "int8")
x_test["CryoSleep"] = x_test["CryoSleep"].astype('int8')
x_test["Cabin"] = (x_test["Cabin"] == "P").astype('int8')
x_test["VIP"] = x_test["VIP"].astype('int8')
x_test_sc = x_test[["Age", "RoomService", "FoodCourt", "ShoppingMall", "Spa", "VRDeck"]]
x_test_sc = pd.DataFrame(scl.transform(x_test_sc), columns = x_test_sc.columns, index = x_test_sc.index)
x_test[["Age", "RoomService", "FoodCourt", "ShoppingMall", "Spa", "VRDeck"]] = x_test_sc

In [ ]:
x_test = x_test.drop("PassengerId", axis = 1)

In [ ]:
x_test = x_test.drop("Name", axis = 1)

In [ ]:
x_test

In [ ]:
x_train

In [ ]:
y_train = y_train.astype("int8")

y_test = y_test.astype("int8")
y_test, y_train

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, f1_score, classification_report

In [ ]:
model1 = LogisticRegression()
model1.fit(x_train, y_train)
accuracy_score(y_train, model1.predict(x_train)), accuracy_score(y_test, model1.predict(x_test))

In [ ]:
model2 = GaussianNB()
model2.fit(x_train, y_train)
accuracy_score(y_train, model2.predict(x_train)), accuracy_score(y_test, model2.predict(x_test))

In [ ]:
model3 = KNeighborsClassifier(n_neighbors=31)
model3.fit(x_train, y_train)
accuracy_score(y_train, model3.predict(x_train)), accuracy_score(y_test, model3.predict(x_test))